migrations/20190310135013-inital-ddl.js, migrations/sqls/20190310135013-inital-ddl-down.sql, migrations/sqls/20190310135013-inital-ddl-up.sql
I added the intial tables. The fields them might change depending ongoing conversations with Vicky and Luis.
=> added few tables

frontend/add-client/client-source.component.tsx, frontend/add-client/global-background.component.tsx, frontend/add-client/income-information.component.tsx, frontend/add-client/personal-information.component.tsx, frontend/add-client/services.component.tsx, frontend/styleguide.component.tsx
=> Moving Next Step button to the right of Go Back. Resolves #23.

frontend/add-client/add-client.component.tsx, frontend/add-client/global-background.component.tsx
=> Changing "Both" to "English and Spanish." Resolves #21.

frontend/add-client/add-client.component.tsx, frontend/add-client/services.component.tsx
=> Renaming service to "Community engagement and organizing". Resolves #19.

api-docs/create-client.md, api-docs/list-services.md, backend/apis/clients/add-client.api.js, backend/apis/clients/client-duplicates.api.js, backend/apis/services/list-services.api.js, backend/apis/utils/transform-utils.js, backend/apis/utils/validation-utils.js, backend/server.js, frontend/add-client/add-client.component.tsx, frontend/add-client/confirm.component.tsx, frontend/add-client/services.component.tsx, migrations/20190512164549-services-list.js, migrations/sqls/20190508233238-clients-up.sql, migrations/sqls/20190512164549-services-list-down.sql, migrations/sqls/20190512164549-services-list-up.sql
This PR is part 2 of 3 for the remaining work on getting the Add Client feature storing everything in the database. We already have contactInformation and demographics being stored in the db, this one adds the intakeServices (CU services that the client is interested in) to the Add Client api.
=> Intake data

frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx
Minor changes made in regards to issue #52.
Also adding change to structure proposal to issue notes.
=> corrected a typo and moved e-mail and city/state fields

frontend/add-client/add-client.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx
added household under 18 field
added register to vote field (need to add toggle based on eligibility)
minor copy editing changes to labels to follow wording on form and consistent casing.
=> Issue 52 client form syncing 02

frontend/add-client/add-client.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx
Added toggle functionality for register to vote question if eligible to vote is marked
=> Issue 52 client form syncing 03

frontend/add-client/add-client.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx, frontend/add-client/services.component.tsx
services.component.tsx
-  removed PrEPClinic
-  removed ITIN renewal
-  removed VITA
-  removed voter registration service checkbox
-  added reference
-  added other
-  matched wording and casing to form
=> Issue 52 client form syncing 04

frontend/add-client/add-client.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx, frontend/add-client/services.component.tsx
go back fixed on demographic, contact info, client source
still need to fix it on services
=> Issue 50 02

api-docs/README.md, api-docs/create-client.md, api-docs/get-client.md, backend/apis/clients/add-client.api.js, backend/apis/clients/get-client.api.js, backend/apis/utils/validation-utils.js, frontend/add-client/add-client.component.tsx, frontend/add-client/confirm.component.tsx, frontend/add-client/finished.component.tsx, frontend/root.component.tsx, frontend/util/easy-fetch.js, frontend/view-client/view-client.component.tsx
=> Beginnings of the View Client page.

api-docs/update-client.md, backend/apis/clients/add-client.api.js, backend/apis/clients/get-client.api.js, backend/apis/clients/update-client.api.js, backend/apis/services/list-services.api.js, backend/apis/utils/validation-utils.js, backend/server.js, frontend/add-client/add-client.component.tsx, frontend/add-client/check-duplicate.component.tsx, frontend/add-client/finished.component.tsx, frontend/add-client/form-inputs/basic-information-inputs.component.tsx, frontend/add-client/list-duplicates.component.tsx, frontend/styleguide.component.tsx, frontend/view-edit-client/client-section.component.tsx, frontend/view-edit-client/view-client.component.tsx, frontend/view-edit-client/view-edit-basic-info.component.tsx
=> View client 3

frontend/add-client/add-client.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/finished.component.tsx, frontend/add-client/list-duplicates.component.tsx, frontend/add-client/services.component.tsx, frontend/home/home-card.component.tsx, frontend/home/home.component.tsx, frontend/navbar/navbars.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/navbar/topnav.component.tsx, frontend/page-header.component.tsx, frontend/report-issue/report-issue-success.component.tsx, frontend/styleguide.component.tsx
add client css updates to accommodate chrome fix
=> Compatibility attempt 2 02

frontend/home/home-card.component.tsx, frontend/home/home.component.tsx, frontend/navbar/navbars.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/navbar/topnav.component.tsx, frontend/page-header.component.tsx, frontend/styleguide.component.tsx
Reset the changes made in browser-compatibility branch and redid changes in rem with the fix to 10px for chrome. I think it also has resolved the mobile view. Changes are on the sidebar and homepage only so far.
=> Compatibility attempt 2 01

frontend/add-client/add-client.component.tsx, frontend/add-client/form-inputs/contact-information-inputs.component.tsx, frontend/util/city-input.component.tsx
=> added up, down, enter, and refocus needed

api-docs/README.md, api-docs/get-client-audit.md, backend/apis/clients/client-audit.api.js, backend/server.js, frontend/view-edit-client/audit-summary-section.component.tsx, frontend/view-edit-client/view-client.component.tsx, frontend/view-edit-client/view-edit-basic-info.component.tsx, frontend/view-edit-client/view-edit-contact-info.component.tsx, frontend/view-edit-client/view-edit-demographics-info.component.tsx, frontend/view-edit-client/view-edit-intake-info.component.tsx, package.json, yarn.lock
Ignore how awful the UX looks here. This PR shows how many updates the individual sections of the contact have had, and who was the last one to update them.
=>  Showing number of updates and who last updated contact information 

backend/apis/clients/list-clients.api.js, backend/apis/utils/validation-utils.js
view client list query created
=> api query created

frontend/client-list/client-list.component.tsx, frontend/client-list/table/clients-table.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-list/toolbar/desktop-table-toolbar-component.tsx, frontend/client-list/toolbar/mobile-clients-table-toolbar.component.tsx, frontend/home/home.component.tsx, frontend/navbar/navbars.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/navbar/use-full-width.hook.tsx, frontend/page-header.component.tsx, frontend/root.component.tsx, frontend/styleguide.component.tsx, frontend/util/use-is-mobile.hook.tsx, frontend/util/use-query-param-state.hook.tsx, package.json, yarn.lock
=> Beginnings of client list.

frontend/add-client/form-inputs/demographic-information-inputs.component.tsx, frontend/styleguide.component.tsx, frontend/view-edit-client/audit-summary-section.component.tsx, frontend/view-edit-client/client-section.component.tsx, frontend/view-edit-client/view-edit-basic-info.component.tsx, frontend/view-edit-client/view-edit-contact-info.component.tsx, frontend/view-edit-client/view-edit-demographics-info.component.tsx, frontend/view-edit-client/view-edit-intake-info.component.tsx
=> Making view/edit client look better

api-docs/list-clients.md, frontend/client-list/client-list.component.tsx, frontend/client-list/table/clients-table.component.tsx, frontend/client-list/table/desktop-clients-table.component.tsx, frontend/client-list/table/mobile-clients-table.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-list/toolbar/desktop-table-toolbar-component.tsx, frontend/navbar/sidebar.component.tsx, frontend/styleguide.component.tsx, frontend/util/formatters.tsx, frontend/view-edit-client/view-edit-contact-info.component.tsx
=>  Client table mostly implemented 

api-docs/list-clients.md, backend/apis/clients/get-client.api.js, backend/apis/clients/list-clients.api.js, backend/apis/utils/validation-utils.js, frontend/client-list/client-list.component.tsx, frontend/client-list/table/desktop-clients-table.component.tsx
=> Integrating client list with backend

.babelrc, backend/apis/clients/list-clients.api.js, frontend/client-list/client-list.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-list/toolbar/desktop-table-toolbar-component.tsx, frontend/client-search/client-search-dsl.helpers.test.tsx, frontend/client-search/client-search-dsl.helpers.tsx, frontend/client-search/client-search-input.component.tsx, frontend/util/use-query-param-state.hook.tsx, jest.config.json, package.json, yarn.lock
=> Searching in client list now implemented.

backend/apis/clients/client-duplicates.api.js
=> Switching duplicates api to use checkValid. Resolves #107.

backend/apis/clients/add-client.api.js, backend/apis/clients/update-client.api.js
#76 is already fixed, but we aren't validating the request to verify that it is fixed.
=> Validating that housingStatus is sent up in reqest. See #76.

frontend/growls/error-listener.tsx, frontend/growls/growls.component.tsx, frontend/report-issue/report-issue.component.tsx, frontend/root.component.tsx, frontend/styleguide.component.tsx
Resolves #113 
This code makes it so that errors thrown correctly by our code will be surfaced to users of the App and give them a chance to report the error, including any debugging/stacktrace info that javascript gives us about the error.
=> Implementing growls and default error handling

frontend/client-list/client-list.component.tsx
=> Fixing bug where client list errantly shows empty state. Resolves #119.

frontend/client-list/client-list.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-search/client-search-dsl.helpers.test.tsx, frontend/client-search/client-search-dsl.helpers.tsx, frontend/client-search/client-search-input.component.tsx, package.json
=> Preserving client list search on refresh. Resolves #114.

migrations/20190607164137-clear-test-data.js, migrations/sqls/20190607164137-clear-test-data-down.sql, migrations/sqls/20190607164137-clear-test-data-up.sql
We will merge this around 3-6pm today, which will signify the end of the "trial" week and the beginning of the db for reals.
=> Clearing all data from the database, except users. For CU DB launch!

frontend/client-search/client-search-input.component.tsx
=> search in client list now clearable

backend/apis/clients/add-client.api.js, frontend/add-client/form-inputs/contact-information-inputs.component.tsx
=> Making email field optional. Resolves #128.

frontend/util/city-input.component.tsx
Removed onClick to prevent crashing issue until can be resolved fully.
=> Temporary fix for issue 125

frontend/util/city-input.component.tsx
=> Adding click listener to popup. Resolves #140

frontend/add-client/form-inputs/contact-information-inputs.component.tsx
Looks like the default state being set to UT was already in place, just needed to switch the order in the form. 
Issue #142
=> state and city switched

frontend/view-edit-client/client-section.component.tsx
=> possible solution to 138

api-docs/client-activity-log.md, backend/apis/clients/activity-log.utils.js, backend/apis/clients/add-client.api.js, backend/apis/clients/get-activity-logs.api.js, backend/apis/clients/insert-client.utils.js, backend/apis/clients/update-client.api.js, backend/server.js, frontend/add-client/form-inputs/contact-information-inputs.component.tsx, migrations/20190629230418-activity-log.js, migrations/sqls/20190629230418-activity-log-down.sql, migrations/sqls/20190629230418-activity-log-up.sql
See #69. This will eventually turn into a way for people to store "case notes"
=> Beginnings of client "activity record". See #69.

backend/apis/clients/add-client.api.js
=> Fix typo in add client api. Resolves #162.

backend/apis/clients/list-clients.api.js, frontend/client-list/client-list.component.tsx
=> Fix bugs related to client list page. Resolves #136.

frontend/client-list/client-list.component.tsx, frontend/client-list/table/desktop-clients-table.component.tsx
See #139. Resolved front end issue showing today's date instead of date created
=> fixed date in client list - resolves #139

frontend/report-issue/report-issue-success.component.tsx, frontend/report-issue/report-issue.component.tsx, frontend/root.component.tsx
=> Adding temporary "report issue" pages for incomplete features. Resolves #145.

api-docs/client-activity-log.md, backend/apis/clients/add-client.api.js, backend/apis/clients/client-logs/activity-log.utils.js, backend/apis/clients/client-logs/create-activity-log.api.js, backend/apis/clients/client-logs/delete-activity-logs.api.js, backend/apis/clients/client-logs/get-activity-logs.api.js, backend/apis/clients/insert-client.utils.js, backend/apis/clients/update-client.api.js, backend/apis/utils/validation-utils.js, backend/server.js
This implements the  API that creates case notes. I also moved some files around into a new folder which accounts for many of the other changes.
=> Implementing creation of case notes.

frontend/client-search/single-client/single-client-search-input.component.tsx, frontend/root.component.tsx, frontend/view-edit-client/case-notes/add-case-note.component.tsx, frontend/view-edit-client/client-history/client-history.component.tsx, package.json, webpack.config.js, yarn.lock
This implements adding a case note through the sidebar. The main new functionality is the "Single Client Input Search" which will be reused for adding a client interaction and possibly for other things, too.
=> More progress on global add case note

.babelrc, package.json, yarn.lock
=> Fixing Edge by using babel preset env

.eslintrc, frontend/add-client/services.component.tsx, frontend/styleguide.component.tsx, frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx, package.json, yarn.lock
=> Implementing adding multiple interactions at once. Resolves #182.

api-docs/list-services.md, backend/apis/services/list-services.api.js, migrations/20190726234757-programs.js, migrations/sqls/20190726234757-programs-down.sql, migrations/sqls/20190726234757-programs-up.sql
We should wait for Vicky, Luis, and Leonel to get back to us before merging this one. Once we merge it, it will run a data migration on the prod database with all the new programs and services.
=>  Adding programs into the services API 

api-docs/list-clients.md, backend/apis/clients/list-clients.api.js, backend/apis/utils/validation-utils.js, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-search/client-list/client-search-dsl.helpers.test.tsx, frontend/client-search/client-list/client-search-dsl.helpers.tsx, frontend/client-search/client-list/client-search-input.component.tsx, frontend/client-search/single-client/single-client-search-input.component.tsx, frontend/styleguide.component.tsx
=> Advanced search and searching by new fields. Resolves #137

migrations/20190806200938-issue-202.js, migrations/sqls/20190806200938-issue-202-down.sql, migrations/sqls/20190806200938-issue-202-up.sql
=> More adjustments to programs/services list. Resolves #202.

api-docs/client-activity-log.md, api-docs/client-interactions.md, api-docs/list-clients.md, backend/apis/clients/add-client.api.js, backend/apis/clients/list-clients.api.js, backend/apis/utils/validation-utils.js, backend/server.js, frontend/add-client/check-duplicate.component.tsx, frontend/add-client/form-inputs/intake-services-inputs.component.tsx, frontend/add-client/services.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-search/client-list/client-search-dsl.helpers.test.tsx, frontend/client-search/client-list/client-search-dsl.helpers.tsx, frontend/client-search/client-list/client-search-input.component.tsx, frontend/client-search/single-client/single-client-search-input.component.tsx, frontend/growls/error-listener.tsx, frontend/styleguide.component.tsx, frontend/util/city-input.component.tsx, frontend/util/state-select.component.tsx, frontend/view-edit-client/client-home/view-edit-demographics-info.component.tsx, migrations/20190806200938-issue-202.js, migrations/20190806211241-client-interaction.js, migrations/sqls/20190726234757-programs-up.sql, migrations/sqls/20190806200938-issue-202-down.sql, migrations/sqls/20190806200938-issue-202-up.sql, migrations/sqls/20190806211241-client-interaction-down.sql, migrations/sqls/20190806211241-client-interaction-up.sql, package.json, yarn.lock
=> progress update and questions

frontend/add-client/add-client.component.tsx, frontend/util/time-duration-input.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Working on frontend for client interactions. See #183.

frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Adding instructions for Financial Coach goals. Resolves #190.

frontend/view-edit-client/client-history/client-history.component.tsx
=> Adding client interactions to client history page. Resolves #181

backend/apis/clients/client-logs/delete-activity-logs.api.js, backend/apis/clients/client-logs/get-activity-logs.api.js
=> Changing deletion of client logs to be a soft delete. Resolves #186

backend/apis/clients/client-logs/patch-activity-log.api.js, backend/server.js
This API is only going to be used for updating case notes. Not for updating client interactions.
=> Implement PATCH client logs. For updating case notes.

frontend/rich-text/full-rich-text-editor.component.tsx, frontend/util/easy-fetch.ts, frontend/util/modal.component.tsx, frontend/view-edit-client/case-notes/edit-case-note.component.tsx, frontend/view-edit-client/client-history/client-history-filters.component.tsx, frontend/view-edit-client/client-history/client-history.component.tsx, frontend/view-edit-client/client-history/edit-log.component.tsx
See #185. In the below gif, an error pops up because the backend for modifying client logs is not yet implemented.
=> Setting up frontend to modify/delete client logs. See #185.

api-docs/client-interactions.md, backend/apis/default-404.api.js, backend/server.js, frontend/client-search/single-client/single-client-search-input.component.tsx, frontend/rich-text/full-rich-text-editor.component.tsx, frontend/util/time-duration-input.component.tsx, frontend/view-edit-client/case-notes/add-case-note.component.tsx, frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Finishing frontend creation of interactions. Resolves #183

backend/apis/clients/client-logs/activity-log.utils.js, backend/apis/clients/client-logs/delete-activity-logs.api.js, backend/apis/clients/client-logs/get-activity-logs.api.js, backend/apis/clients/client-logs/patch-activity-log.api.js, frontend/util/modal.component.tsx, frontend/view-edit-client/client-history/client-history-filters.component.tsx, frontend/view-edit-client/client-history/client-history.component.tsx, frontend/view-edit-client/client-history/view-outdated-log.component.tsx, migrations/20190818193754-client-log-new-version.js, migrations/sqls/20190818193754-client-log-new-version-down.sql, migrations/sqls/20190818193754-client-log-new-version-up.sql
Similar behavior will apply for client interactions.
=> Inserting new client log instead of updating existing one.

backend/apis/clients/client-interactions/client-interaction.utils.js, backend/apis/clients/client-interactions/create-client-interaction.api.js, backend/apis/clients/client-interactions/get-client-interaction.api.js, backend/apis/clients/client-interactions/patch-client-interaction.api.js, backend/server.js, frontend/view-edit-client/client-history/edit-log.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Implementing PATCH interaction. Resolves #178.

backend/apis/clients/client-interactions/client-interaction.utils.js, backend/apis/clients/client-interactions/create-client-interaction.api.js, backend/apis/clients/client-interactions/delete-client-interaction.api.js, backend/apis/clients/client-interactions/patch-client-interaction.api.js, backend/server.js, frontend/growls/error-listener.tsx, frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Implementing delete client interaction. Resolves #179.

frontend/client-search/single-client/single-client-search-input.component.tsx
=> added id to client interaction search dropdown

frontend/view-edit-client/case-notes/add-case-note.component.tsx, frontend/view-edit-client/client-history/client-history.component.tsx
intended to resolve issue #233
=> instructions added to case note form

backend/apis/clients/update-client.api.js, backend/apis/utils/validation-utils.js
`validArray` wasn't working properly, so i fixed it. Also, there were some straight up bugs in update-client.api.js referencing `err` variables taht didn't exist.
=> Fixing bugs with PATCH client validation

frontend/client-list/table/mobile-clients-table.component.tsx
=> Adding client id to mobile clients list. Resolves #240.

api-docs/create-client.md, backend/apis/clients/add-client.api.js, backend/apis/clients/update-client.api.js, frontend/add-client/form-inputs/demographic-information-inputs.component.tsx
=> Adding separated as a civil status. Resolves #199.

backend/apis/clients/update-client.api.js, frontend/client-search/single-client/single-client-search-input.component.tsx, frontend/util/use-force-update.tsx, frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/update-interested-services.component.tsx, frontend/view-edit-client/view-client.component.tsx
=> Update intake services when adding interaction. Resolves #234

frontend/add-client/confirm.component.tsx, frontend/add-client/form-inputs/basic-information-inputs.component.tsx, frontend/add-client/form-inputs/contact-information-inputs.component.tsx
See #212 
Also I added a fix for #172 into here too:
=> Trimming first and last name for new clients. Resolves #212.

backend/apis/clients/list-clients.api.js, frontend/client-list/client-list.component.tsx, frontend/client-list/table/clients-table.component.tsx, frontend/client-list/table/desktop-clients-table.component.tsx
=> Allow for sorting client list by id, name, or birthday.

frontend/home/home.component.tsx, frontend/view-edit-client/integrations/integrations.component.tsx, frontend/view-edit-client/view-client.component.tsx
=> Adding integrations route, behind feature toggle

.gitignore, migrations/20190910195603-services-update-09102019.js, migrations/sqls/20190512164549-services-list-down.sql, migrations/sqls/20190910195603-services-update-09102019-down.sql, migrations/sqls/20190910195603-services-update-09102019-up.sql
To address service changes on issues #260, #261, #262, and #263.
=> services modifications for issues 260 to 263

api-docs/client-interactions.md
Separated the fixes that came up in client interactions while working on the leads and events.
=> fix to client interactions apidocs

frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> defaults added to client interactions

api-docs/leads.md, frontend/add-client/confirm.component.tsx
change highlight makes it look bigger than it is. Only the ( to [ on the get all and tabbing over changed
=> fix lead apidocs type

frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/util/dropdown-menu-modal.component.tsx
For issue #280 
Also creates a reusable drop down menu component so we don't have to recreate one when we do the leads front end and reporting front end.
=> fix to bulk action drop down menu

README.md, api-docs/README.md, backend/apis/login.api.js, backend/apis/utils/transform-utils.js, backend/index-html.js, frontend/util/user.context.tsx, package.json, yarn.lock
=> Allowing for local dev without Google Auth. Resolves #286.

migrations/20191002015049-leads-and-events.js
Correction to events migration that I had previous missed.
=> event migrate fix

api-docs/events.md, backend/apis/events/get-event.api.js, backend/server.js, migrations/20191012044609-events-correction.js, migrations/sqls/20191012044609-events-correction-down.sql, migrations/sqls/20191012044609-events-correction-up.sql
=> events api - get one event

api-docs/events.md
the createdby and modifiedby were missing in some of the actions.
=> fix to events api docs for missing info

api-docs/leads.md, backend/apis/leads/get-lead.api.js, backend/server.js
Part of issue #308 
api for get one lead and a few related corrections
=> leads api - get one lead

backend/apis/events/list-events.api.js, backend/server.js
part of issue #309 
list all events
fixed error, ready for review.
=> events api - list events

frontend/home/home.component.tsx, frontend/leads-list/lead-list.component.jsx, frontend/navbar/sidebar.component.tsx, frontend/root.component.tsx
Part of issue #316 
Putting up the placeholder suggestion form
=> lead list page setup

api-docs/leads.md, backend/apis/leads/get-lead.api.js, backend/apis/leads/list-leads.api.js, backend/server.js
part of issue #308 
also noticed the full name of the lead was left off the get one
=> leads api - list leads

frontend/leads-list/table/desktop-leads-table.component.tsx
Changing out the text copied over from clients list
=> Fixing typo in leads list

backend/apis/clients/add-client.api.js, backend/apis/events/add-event.api.js, backend/server.js, package.json
=> add events api 

frontend/view-edit-client/case-notes/add-case-note.component.tsx
=> Fixing react warning

frontend/add-leads/add-event-step.component.tsx, frontend/add-leads/add-lead-row.component.tsx, frontend/add-leads/add-leads-step.component.tsx, frontend/add-leads/add-leads-table.component.tsx, frontend/add-leads/add-leads.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/navbar/use-full-width.hook.tsx, frontend/root.component.tsx
This PR is the beginning of the UI for the Add Leads feature. I took @jenseng's commit and adjusted it to set us up for adding events, too.
=> Beginnings of Add Leads

api-docs/events.md, backend/apis/events/add-event.api.js, backend/apis/events/get-event.api.js, backend/apis/events/list-events.api.js, migrations/20191109223917-total-attendance.js, migrations/sqls/20191109223917-total-attendance-down.sql, migrations/sqls/20191109223917-total-attendance-up.sql
attendance was misspelled everywhere. Also, there were two bugs in the POST /api/events api.
=> Fixing typo and bugs in POST /api/events

api-docs/events.md, backend/apis/events/list-events.api.js
I'm going to display all the CU events, and want the order to be based on the event date instead of the insertion date.
=> Order list leads

backend/apis/events/delete-event.api.js, backend/server.js
See https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/master/api-docs/events.md#delete-a-single-event
=> Implementing DELETE /api/events/:id

frontend/add-leads/add-event-step.component.tsx, frontend/add-leads/add-lead-step-header.component.tsx, frontend/add-leads/add-leads.component.tsx
=> Implementing the ui for creating events.

frontend/add-leads/add-event-step.component.tsx, frontend/add-leads/add-lead-step-header.component.tsx, frontend/add-leads/add-leads-step.component.tsx, frontend/add-leads/add-leads.component.tsx, frontend/root.component.tsx, package.json
I decided to make the create event and create leads steps their own routes. This resulted in some refactoring. I also finished implementing choosing an existing event (in addition to the already-implemented create new event)
=> Reuse existing event

backend/apis/leads/update-lead.api.js, frontend/view-edit-lead/edit-lead-inputs/lead-contact-information-inputs.component.tsx, frontend/view-edit-lead/lead-home/lead-home.component.tsx, frontend/view-edit-lead/lead-home/view-edit-basic-lead-info.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-contact-info.component.tsx, frontend/view-edit-lead/view-lead.component.tsx
=> update lead contact info

backend/apis/health.api.js, backend/server.js, package-lock.json
=> adding a /health endpoint for a healtch check for eb

.gitignore, api-docs/client-files.md
=> Looking for input on api-docs for client-files

api-docs/get-interactions-hours.md
Response for API call. Please review request url🙏
=> doc - new api to get sum of interaction hours

.ebextensions/03-https-redirect-node.config
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html
=> Think this should be commands and not command

frontend/view-edit-lead/lead-home/view-edit-basic-lead-info.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-contact-info.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-event-info.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-services-info.component.tsx
part of issue #349 
added isEditing to the useReducer where missing
fixed some redundant .props
=> touch ups to lead updates

frontend/client-list/table/desktop-clients-table.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/navbar/topnav.component.tsx, frontend/page-header.component.tsx
=> Making client list print correctly on desktop. Resolves #376.

backend/apis/leads/update-lead.api.js, frontend/util/date-input.component.tsx, frontend/view-edit-client/client-home/view-edit-intake-info.component.tsx, frontend/view-edit-lead/edit-lead-inputs/contact-attempt-input.component.tsx, frontend/view-edit-lead/edit-lead-inputs/lead-contact-status-inputs.component.tsx, frontend/view-edit-lead/lead-home/lead-home.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-contact-status.component.tsx
=> Update lead contact attempts

backend/apis/clients/add-client.api.js, backend/apis/clients/insert-client.utils.js, frontend/add-client/add-client.component.tsx, frontend/leads-list/table/desktop-leads-table.component.tsx, frontend/leads-list/table/lead-services-cell.component.tsx, frontend/root.component.tsx, frontend/styleguide.component.tsx, frontend/view-edit-lead/convert-lead-to-client.component.tsx, frontend/view-edit-lead/lead-home/convert-to-client-card.component.tsx, frontend/view-edit-lead/lead-home/lead-home.component.tsx, frontend/view-edit-lead/view-lead.component.tsx
=> Converting leads to clients

README.md, migrations/20200216173728-snap-program.js, migrations/sqls/20200216173728-snap-program-down.sql, migrations/sqls/20200216173728-snap-program-up.sql
=> Moving SNAP into its own program. Resolves #362.

migrations/20200216175943-issue-443.js, migrations/sqls/20200216175943-issue-443-down.sql, migrations/sqls/20200216175943-issue-443-up.sql
=> Adding and renaming services for Mammograms, Sex Ed, etc. Resolves #443.

backend/apis/leads/add-leads.api.js, frontend/add-leads/add-lead-row.component.tsx, frontend/add-leads/add-leads-step.component.tsx, frontend/view-edit-lead/edit-lead-inputs/basic-lead-information-inputs.component.tsx, frontend/view-edit-lead/edit-lead-inputs/lead-contact-information-inputs.component.tsx, frontend/view-edit-lead/lead-home/view-edit-basic-lead-info.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-contact-info.component.tsx
=> Making age, gender, and zip not required fields for Leads. Resolves #436

api-docs/list-clients.md, backend/apis/clients/list-clients.api.js, frontend/client-list/toolbar/client-search-input.component.tsx, frontend/client-list/toolbar/program-or-service.component.tsx, frontend/util/list-search/search-dsl.helpers.tsx
=> Add ability to search client list by interest in service.

api-docs/leads.md, backend/apis/clients/list-clients.api.js, backend/apis/leads/list-leads.api.js, frontend/client-list/toolbar/program-or-service.component.tsx, frontend/leads-list/lead-list.component.tsx, frontend/leads-list/table/desktop-leads-table.component.tsx, frontend/leads-list/table/lead-services-cell.component.tsx, frontend/leads-list/table/leads-table.component.tsx, frontend/leads-list/toolbar/lead-search-input.component.tsx, frontend/leads-list/toolbar/leads-table-toolbar.component.tsx
This started out as part of making the SMS feature, which requires the mysql query to be reusable. But then I found that we were doing n + 1 database queries, so I consolidated it down to just one. Also I added in the ability to filter by interest in a specific service.
=> Leads list refactor - perf, search by service, reusable mysql query.

backend/apis/leads/add-leads.api.js, frontend/add-leads/add-event-step.component.tsx, frontend/add-leads/add-leads-step.component.tsx, frontend/add-leads/add-leads.component.tsx
=> Add ability to create leads not connected to an event. Resolves #440.

api-docs/check-duplicate-client.md, backend/apis/clients/client-duplicates.api.js, frontend/add-client/add-client.component.tsx, frontend/add-client/check-duplicate.component.tsx, frontend/add-client/confirm.component.tsx, frontend/add-client/list-duplicates.component.tsx, frontend/view-edit-lead/convert-lead-to-client.component.tsx, frontend/view-edit-lead/lead-home/convert-to-client-card.component.tsx, frontend/view-edit-lead/lead-home/lead-home.component.tsx
=> Make it much easier to convert leads to clients. Resolves #471.

frontend/bulk-sms/bulk-sms-modal.component.tsx
=> Adding preview step to bulk texts. Resolves #461.

api-docs/events.md, backend/apis/events/get-event.api.js, frontend/view-edit-events/event-home/view-event-stats.component.tsx, frontend/view-edit-events/view-event.component.tsx
=> Improving event statistics table. Resolves #456.

frontend/leads-list/lead-list.component.tsx, frontend/leads-list/table/desktop-leads-table.component.tsx, frontend/leads-list/table/leads-table.component.tsx, frontend/leads-list/toolbar/lead-search-input.component.tsx, frontend/leads-list/toolbar/leads-table-toolbar.component.tsx
=> Fixing advanced search scrolling in Leads List. Resolves #455.

frontend/navbar/navbars.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/util/use-local-storage.hook.tsx
=> Adding ability to collapse sidebar

backend/index-html.js, frontend/page-header.component.tsx, frontend/root.component.tsx, frontend/styleguide.component.tsx, frontend/util/user-mode.context.tsx, frontend/util/user.context.tsx
This gives the user visual indication of whether they are in "Immigration Mode" or not. When in immigration mode, access to client interactions, files, and notes will be restricted.
=> User mode ui

backend/apis/clients/client-logs/activity-log.utils.js, backend/apis/clients/client-logs/create-activity-log.api.js, backend/apis/tags/tag.utils.js
=> Fixing issue with creating clients. Resolves #509.

backend/apis/clients/client-logs/activity-log.utils.js
=> Fix issue creating client interactions. Resolves #511.

backend/apis/reports/ages-and-genders-report.api.js, frontend/reports/ages-and-genders/ages-and-genders-results.components.tsx
The report did not account for when Leads have unknown gender. See #515
=> Fixing age and gender report when leads have unknown gender. Resolves #515

backend/apis/leads/add-leads.api.js, backend/apis/utils/transform-utils.js, frontend/add-leads/add-leads-step.component.tsx, frontend/leads-list/table/desktop-leads-table.component.tsx, frontend/view-edit-lead/lead-home/view-edit-lead-contact-status.component.tsx, migrations/20200508231148-lead-signup-date.js, migrations/sqls/20200508231148-lead-signup-date-down.sql, migrations/sqls/20200508231148-lead-signup-date-up.sql
=> Fixing issue where lead dateOfSignUp was hard coded. Resolves #508.

frontend/leads-list/toolbar/lead-search-input.component.tsx
Resolves https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/505
=> Adding event date to leads advanced search

backend/apis/clients/files/add-client-files.api.js, backend/apis/clients/files/file-helpers.js, backend/apis/clients/files/presigned-file-upload.api.js, backend/server.js, frontend/client-files/client-files.component.tsx, migrations/sqls/20200511202453-files-up.sql
Uploading client files is now working.
=> Uploading client files is now working

api-docs/events.md, backend/apis/events/update-event.api.js, backend/server.js, frontend/view-edit-events/event-home/view-edit-event-info.component.tsx
=> Implement editing events. Resolves #454.

frontend/view-edit-lead/edit-lead-inputs/contact-attempt-input.component.tsx
=> Add ability to delete lead contact attempt. Resolves #492.

frontend/navbar/sidebar.component.tsx
=> Make sidebar scrollable. Resolves #503.

backend/apis/leads/list-leads.api.js, backend/apis/utils/mysql-utils.js, frontend/leads-list/lead-list.component.tsx, frontend/leads-list/table/desktop-leads-table.component.tsx, frontend/leads-list/table/leads-table.component.tsx, frontend/styleguide.component.tsx, frontend/view-edit-lead/view-lead.component.tsx
=> Show event sources in leads list. Resolves #519.

frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
=> Restrict adding immigration interactions to those with Immigration perm. Resolves #514.

backend/apis/reports/interaction-hours-by-client.api.js, frontend/reports/interaction-hours-by-client/interaction-hours-by-client-params.component.tsx, frontend/reports/interaction-hours-by-client/interaction-hours-by-client-results.component.tsx, frontend/reports/reports.components.tsx, frontend/util/time-duration-helpers.tsx
=> Make date range inputs easier for interaction report. Resolves #527.

backend/apis/reports/interaction-hours-by-client.api.js, backend/apis/reports/service-interest-report.api.js, frontend/reports/service-interests/service-interests-params.component.tsx
=> Adding date ranges for program/service interest report. Resolves #528.

backend/apis/reports/interactions-by-service.api.js, frontend/reports/interactions-by-service/interactions-by-service-results.component.tsx
=> Fixing time ranges for interaction hours by program/service report. Resolves #554.

README.md, frontend/reports/service-interests/service-interests-params.component.tsx, frontend/reports/service-interests/service-interests-results.component.tsx, frontend/reports/shared/basic-table-report.component.tsx
resolves https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/559.
=> Add explanation for time ranges in Interest in Programs/Services report. Resolves #559

api-docs/client-files.md, backend/apis/clients/files/add-client-files.api.js, backend/apis/clients/files/delete-client-files.api.js, backend/apis/clients/files/get-client-file.api.js, backend/server.js, frontend/client-files/client-file-chip.component.tsx, frontend/client-files/client-file-preview-modal.component.tsx, frontend/client-files/client-file-previewer.component.tsx, frontend/view-edit-client/client-history/client-history.component.tsx, migrations/20200630043822-files-log-type.js, migrations/sqls/20200630043822-files-log-type-down.sql, migrations/sqls/20200630043822-files-log-type-up.sql
=> Adding client history event for file uploads and deletions. Resolves #566

api-docs/check-duplicate-client.md, backend/apis/clients/client-duplicates.api.js
Needed for integration with Suite CRM
=> Not making birthday or gender required for the client duplicates API.

frontend/client-list/client-list.component.tsx, package.json, webpack.config.js
=> Improving performance of client list.

backend/apis/clients/add-client.api.js, backend/apis/clients/insert-client.utils.js, backend/apis/clients/update-client.api.js, backend/apis/utils/patch-utils.js, backend/apis/utils/transform-utils.js, frontend/add-client/check-duplicate.component.tsx, frontend/add-client/client-source.component.tsx, frontend/add-client/contact-information.component.tsx, frontend/add-client/demographic-information.component.tsx, frontend/add-client/form-inputs/basic-information-inputs.component.tsx, frontend/add-client/form-inputs/client-source-inputs.component.tsx, frontend/add-client/form-inputs/contact-information-inputs.component.tsx, frontend/add-client/form-inputs/demographic-information-inputs.component.tsx, frontend/util/city-input.component.tsx, frontend/util/phone-input.component.tsx, frontend/view-edit-client/client-home/view-edit-basic-info.component.tsx, frontend/view-edit-client/client-home/view-edit-contact-info.component.tsx, frontend/view-edit-client/client-home/view-edit-demographics-info.component.tsx, frontend/view-edit-client/client-home/view-edit-intake-info.component.tsx, frontend/view-edit-lead/edit-lead-inputs/lead-contact-information-inputs.component.tsx
See #578. This was caused by adding clients that don't have all the normally required fields, as part of the Suite CRM migration.
=> Fixing issues with editing clients. Resolves #578.

frontend/add-client/form-inputs/contact-information-inputs.component.tsx
=> Fixing issue with creating clients. Resolves #586.

backend/apis/leads/add-leads.api.js, migrations/20200729002805-issue-583.js, migrations/sqls/20200729002805-issue-583-down.sql, migrations/sqls/20200729002805-issue-583-up.sql
=> Fix missing lead signup date. Resolves #583.

backend/apis/clients/list-clients.api.js, frontend/client-list/toolbar/client-search-input.component.tsx, frontend/leads-list/toolbar/lead-search-input.component.tsx
=> Fix bulk text when searching service. Resolves #585.

backend/apis/clients/add-client.api.js
=> Fix issue creating client with unknown civil status. Resolves #592.

frontend/add-client/form-inputs/contact-information-inputs.component.tsx
=> Client side validation of email input. Resolves #594.

.elasticbeanstalk/config.yml, backend/apis/reports/outstanding-invoices.api.js, backend/apis/reports/outstanding-invoices.sql, backend/server.js, frontend/reports/outstanding-invoices/outstanding-invoices-params.component.tsx, frontend/reports/outstanding-invoices/outstanding-invoices-results.component.tsx, frontend/reports/reports.components.tsx, frontend/reports/shared/use-reports-api.tsx
Adding outstanding invoices report.
=> Outstanding invoices report

backend/apis/invoices/get-invoice-pdf.api.js
=> Don't show false on invoice pdfs. Fixes #634.

api-docs/partners.md, api-docs/referrals.md, migrations/20201003180941-referrals.js, migrations/sqls/20201003180941-referrals-down.sql, migrations/sqls/20201003180941-referrals-up.sql
=> DB Schema and API contract for referrals.

api-docs/partners.md, backend/apis/partners/create-partner-service.api.js, backend/apis/partners/create-partner-service.sql, backend/apis/partners/create-partner.api.js, backend/apis/partners/create-partner.sql, backend/apis/partners/get-partner-list.api.js, backend/apis/partners/get-partner-list.sql, backend/apis/partners/get-partner-service.sql, backend/apis/partners/get-partner.sql, backend/apis/partners/update-partner-service.api.js, backend/apis/partners/update-partner-service.sql, backend/apis/partners/update-partner.api.js, backend/apis/partners/update-partner.sql, backend/server.js
=> Implement apis for partners and partner services

.prettierignore, backend/apis/reports/poverty-line.api.js, frontend/root.component.tsx
https://github.com/JustUtahCoders/comunidades-unidas-internal/commit/f98f681cd7c79e0bb6ae58562dff314e5c6f7e68 broke the build, as shown in https://travis-ci.org/github/JustUtahCoders/comunidades-unidas-internal/builds/732608273#L224. It upgraded prettier without reformatting all the files. The upgrade to prettier changed how things work. To fix, I ran `yarn format` and then made sure to ignore all files that prettier doesn't understand (like image files)
=> Fix formatting issues.

frontend/admin/admin-settings.component.tsx, frontend/admin/admin-settings.css, frontend/admin/partners/create-new-partner-service.component.tsx, frontend/admin/partners/create-new-partner.component.tsx, frontend/admin/partners/editable-partner-row.component.tsx, frontend/admin/partners/editable-partner-service-row.component.tsx, frontend/admin/partners/partner-inputs.component.tsx, frontend/admin/partners/partner-inputs.css, frontend/admin/partners/partner-service-inputs.component.tsx, frontend/admin/partners/partners.component.tsx, frontend/admin/partners/partners.css, frontend/home/home.component.tsx, frontend/navbar/sidebar.component.tsx, frontend/programs-and-services/editable-program-row.component.tsx, frontend/root.component.tsx, frontend/styleguide.component.tsx
=> Implement admin UI for modifying CU partners.

api-docs/referrals.md, backend/apis/clients/referrals/add-client-referral.api.js, backend/apis/clients/referrals/add-client-referral.sql, backend/server.js, frontend/view-edit-client/client-history/client-history.component.tsx, frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/edit-client-interaction.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx, migrations/20201006184851-referrals-fix.js, migrations/sqls/20201006184851-referrals-fix-down.sql, migrations/sqls/20201006184851-referrals-fix-up.sql
This PR is messy and shows where we should probably refactor things. However, I'm pushing to get this released today so I didn't engage in the refactors.
=> Client referrals

backend/apis/reports/referrals-by-service-report.api.js, backend/apis/reports/referrals-by-service-report.sql, backend/server.js, frontend/reports/referrals-by-service/referrals-by-service-params.component.tsx, frontend/reports/referrals-by-service/referrals-by-service-results.component.tsx, frontend/reports/reports.components.tsx
=> Referrals by service report

api-docs/leads.md, backend/apis/clients/list-clients.api.js, backend/apis/leads/list-leads.api.js, frontend/client-list/toolbar/client-search-input.component.tsx, frontend/client-list/toolbar/program-or-service.component.tsx, frontend/leads-list/toolbar/lead-search-input.component.tsx, frontend/util/list-search/search-dsl.helpers.tsx
See #649. In the screenshot, "Interaction" is the new part.
=> Allow searching for clients who've received an interaction. Resolves #649

api-docs/users.md, backend/apis/users/get-user.sql, backend/apis/users/list-users.api.js, backend/apis/users/list-users.sql, backend/apis/users/patch-user.api.js, backend/apis/users/patch-user.sql, backend/server.js, frontend/admin/admin-settings.component.tsx, frontend/admin/user-permissions/edit-user.component.tsx, frontend/admin/user-permissions/edit-user.css, frontend/admin/user-permissions/user-permissions.component.tsx, frontend/home/home-card.component.tsx, frontend/home/home.component.tsx, frontend/root.component.tsx, frontend/view-edit-client/add-new/client-add-new-info.component.tsx
=> Implement admin ui for user permissions. Resolves #651.

api-docs/client-follow-up.md
Closes: #669 
API documentation for the POST and PATCH request and endpoints for client follow ups.
=> API post and patch request contract for follow ups

migrations/20201028204537-followups-up.js
Migrations file generated to create tables.
=> follow up migration file generated

frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
See #659. As I work on the follow up UI more, I'm probably going to refactor the single-interaction-slat further so that each interaction kind will have its own component. But for now, I just introduced the concept of `interactionKind` and added the question for it.
=> Prompt if interaction is cuService, referral, or followup. Resolves #659

frontend/view-edit-client/interactions/add-client-interaction.component.tsx, frontend/view-edit-client/interactions/edit-client-interaction.component.tsx, frontend/view-edit-client/interactions/follow-up-interaction-inputs.component.tsx, frontend/view-edit-client/interactions/referral-interaction-inputs.component.tsx, frontend/view-edit-client/interactions/service-interaction-inputs.component.tsx, frontend/view-edit-client/interactions/single-interaction-slat.component.tsx
This is a substantial refactor of interactions that makes it a lot easier to add new things to the interactions ui, including follow ups.
The technical debt had piled up here for a while, especially when I bolted on referrals without refactoring, so this addressed a lot of things.
=> Refactoring interactions, so we can implement follow-ups.

backend/apis/clients/client-interactions/delete-client-interaction.api.js, backend/apis/clients/client-logs/activity-log.utils.js, backend/apis/utils/transform-utils.js, backend/server.js, frontend/util/timestamp.helpers.tsx, frontend/view-edit-client/client-history/client-history.component.tsx, frontend/view-edit-client/interactions/service-interaction-inputs.component.tsx
This was pair programmed with Andrea
=> Various interaction fixes.

backend/apis/partners/create-partner.api.js, backend/apis/partners/create-partner.sql, backend/apis/partners/get-partner-list.api.js, backend/apis/partners/get-partner-list.sql, backend/apis/partners/update-partner.api.js, backend/apis/partners/update-partner.sql, frontend/admin/partners/create-new-partner.component.tsx, frontend/admin/partners/editable-partner-row.component.tsx, frontend/admin/partners/editable-partner-service-row.component.tsx, frontend/admin/partners/partner-inputs.component.tsx, frontend/admin/partners/partners.component.tsx, frontend/util/phone-input.component.tsx, frontend/view-edit-client/interactions/referral-interaction-inputs.component.tsx, migrations/20201117023415-add-partner-phone.js, migrations/sqls/20201117023415-add-partner-phone-down.sql, migrations/sqls/20201117023415-add-partner-phone-up.sql
https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/658
- db migration to add phone column to partners table
- update partner APIs to include phone
- add phone input to UI for create/update partner in admin settings
- display phone in partner table in admin settings
- display phone in partner select in client interaction referral form
=> Issue 658: Add phone number to referral partners

backend/apis/clients/follow-ups/create-follow-up.api.js
Previously, a serviceIds array that was empty would result in a server error. This fixes that.
=> Fix bug with creating follow ups that had no services.

api-docs/events.md, migrations/20210115225659-event-materials.js, migrations/sqls/20210115225659-event-materials-down.sql, migrations/sqls/20210115225659-event-materials-up.sql
=> DB Schema for event materials. Resolves #727.

backend/apis/events/add-event.api.js, backend/apis/events/get-event.api.js, backend/apis/events/list-events.api.js, backend/apis/events/update-event.api.js
=> Backend changes for adding materials to events. Resolves #728.

backend/apis/events/list-events.api.js, frontend/event-list/desktop-event-table.component.tsx, frontend/event-list/event-list.component.tsx
=> Show materials distributed in Events List. Resolves #729.

frontend/view-edit-events/event-home/event-home.component.tsx, frontend/view-edit-events/event-home/event-section.component.tsx, frontend/view-edit-events/event-home/view-edit-event-materials.component.tsx, frontend/view-edit-events/view-event.component.tsx
=> Show materials distributed on Event Home page. See #730

frontend/reports/ages-and-genders/ages-and-genders-results.components.tsx
=> Fix gender report

backend/apis/clients/list-clients.api.js, backend/apis/leads/list-leads.api.js, backend/apis/sms/check-bulk-sms.api.js, backend/apis/sms/send-bulk-sms.api.js, frontend/bulk-sms/bulk-sms-modal.component.tsx
=> Support texting only clients or leads. Resolves #748.

frontend/add-leads/referral-inputs.component.tsx
=> Show phone number for parters in lead referrals

backend/apis/reports/poverty-line.api.js, frontend/reports/poverty-line/poverty-line-params.component.tsx, frontend/reports/poverty-line/poverty-line-results.component.tsx, frontend/reports/shared/basic-table-report.component.tsx
=> Updates to poverty line report. Resolves #784

backend/apis/clients/get-client.api.js, backend/apis/clients/get-clients-by-id.sql, backend/apis/clients/list-clients.api.js, backend/apis/reports/ages-and-genders-report.api.js, backend/apis/reports/client-sources-report.api.js, backend/apis/reports/country-of-origin-report.api.js, backend/apis/reports/english-level.api.js, backend/apis/reports/interaction-hours-by-client.api.js, backend/apis/reports/outstanding-invoices.sql, backend/apis/reports/poverty-line.api.js, backend/apis/reports/service-interest-report.api.js, backend/apis/reports/zipcode-report.api.js, frontend/reports/country-of-origin/country-of-origin-results.component.tsx, frontend/reports/interaction-hours-by-client/interaction-hours-by-client-results.component.tsx, frontend/reports/service-interests/service-interests-results.component.tsx, migrations/20210417002233-latest-contact-info.js, migrations/sqls/20210417002233-latest-contact-info-down.sql, migrations/sqls/20210417002233-latest-contact-info-up.sql
=> Fix queries related to latest rows in tables.

backend/apis/reports/interaction-hours-by-client.api.js, backend/apis/reports/interactions-by-service.api.js, backend/apis/reports/outstanding-invoices.sql, backend/apis/reports/revenue-by-service.sql, backend/apis/reports/service-interest-report.api.js, frontend/reports/ages-and-genders/ages-and-genders-params.component.tsx, frontend/reports/client-sources/client-sources-params.component.tsx, frontend/reports/client-zipcode/client-zipcode-params.component.tsx, frontend/reports/country-of-origin/country-of-origin-params.component.tsx, frontend/reports/custom-interaction-questions/custom-interaction-questions-params.component.tsx, frontend/reports/english-levels/english-levels-params.component.tsx, frontend/reports/interaction-hours-by-client/interaction-hours-by-client-params.component.tsx, frontend/reports/interactions-by-service/interactions-by-service-params.component.tsx, frontend/reports/outstanding-invoices/outstanding-invoices-params.component.tsx, frontend/reports/referrals-by-service/referrals-by-service-params.component.tsx, frontend/reports/revenue-by-service/revenue-by-service-params.component.tsx, frontend/reports/service-interests/service-interests-params.component.tsx, frontend/reports/shared/date-preset-inputs.component.tsx
=> Provide Date Range Presets for reports.

backend/apis/clients/list-clients.api.js, frontend/client-list/client-list.component.tsx, frontend/client-list/toolbar/client-search-input.component.tsx, frontend/client-list/toolbar/clients-table-toolbar.component.tsx, frontend/client-list/toolbar/program-or-service.component.tsx, frontend/leads-list/lead-list.component.tsx, frontend/leads-list/toolbar/lead-search-input.component.tsx, frontend/leads-list/toolbar/leads-table-toolbar.component.tsx
Resolves #792. Also makes the search sticky. THis was feedback from the all-staff meeting today
=> Make searches sticky. Fix lead program / service interest search.

frontend/reports/ages-and-genders/ages-and-genders-results.components.tsx, frontend/reports/client-sources/client-sources-results.component.tsx, frontend/reports/shared/basic-table-report.component.tsx, frontend/util/csv-utils.tsx
=> First two Export To CSV buttons in reports. See #789.

frontend/reports/custom-interaction-questions/custom-interaction-questions-results.component.tsx, frontend/reports/referrals-by-service/referrals-by-service-results.component.tsx
=> custom questions & referral by service reports are done

backend/apis/reports/interaction-hours-by-client.api.js, frontend/reports/interaction-hours-by-client/interaction-hours-by-client-results.component.tsx, frontend/reports/shared/use-reports-api.tsx
=> Issue 789-5

frontend/reports/interactions-by-service/interactions-by-service-results.component.tsx, frontend/reports/revenue-by-service/revenue-by-service-results.component.tsx
=> interactions by service & revenue by service done

frontend/view-edit-client/interactions/service-interaction-inputs.component.tsx
=> Fix issue with interactions storing as Citizenship interactions. Resolves #817

backend/apis/clients/client-duplicates.api.js
=> Improve duplicates search. Resolvse #815.

api-docs/events.md, backend/apis/events/add-event.api.js, backend/apis/events/get-event.api.js, backend/apis/events/list-events.api.js, backend/apis/events/update-event.api.js, backend/apis/utils/transform-utils.js, frontend/add-leads/add-event-step.component.tsx, frontend/view-edit-events/event-home/view-edit-event-info.component.tsx, frontend/view-edit-events/event-home/view-event-leads.component.tsx, frontend/view-edit-events/event-home/view-event-stats.component.tsx, frontend/view-edit-events/view-event.component.tsx, migrations/20210607201336-event-attendance-genders.js, migrations/sqls/20210607201336-event-attendance-genders-down.sql, migrations/sqls/20210607201336-event-attendance-genders-up.sql
=> Track event attendance by gender. Resolves #821

frontend/reports/interaction-hours-by-client/interaction-hours-by-client-results.component.tsx
=> Fix interaction hours report (was throwing error). Resolves #824

.elasticbeanstalk/config.yml, .github/workflows/build-and-deploy.yml, README.md
Switches to main, switches to newprod env in aws
=> Deploy fix

frontend/add-client/form-inputs/basic-information-inputs.component.tsx
=> Allow uppercase second names

.elasticbeanstalk/config.yml
See https://github.com/JustUtahCoders/comunidades-unidas-internal/actions/runs/12980077023/job/36196657164
=> Try to fix deploy.
