JustUtahCoders/comunidades-unidas-internal

frontend/add-client/services.component.tsx
frontend/util/city-input.component.tsx

Renaming "Groceries" to "Grocery store tour". Resolves #18.

---

frontend/add-client/form-inputs/basic-information-inputs.component.tsx
frontend/add-client/form-inputs/contact-information-inputs.component.tsx
frontend/add-client/form-inputs/demographic-information-inputs.component.tsx
frontend/add-client/list-duplicates.component.tsx
frontend/util/city-input.component.tsx
frontend/util/phone-input.component.tsx

Changing input fields that we do not want to autocomplete to autoComplete="new-password" did successfully stop the autocomplete and suggest in Chrome without breaking the same in Firefox. 
Ruled out the false, readonly removed on focus, and false input field methods.

possible solutuion for autocomplete chrome issue

---

frontend/add-client/form-inputs/demographic-information-inputs.component.tsx

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#Browser_compatibility and https://bugzilla.mozilla.org/show_bug.cgi?id=888320

Making date of US arrival be month input instead of date

---

frontend/home/home.component.tsx
frontend/navbar/sidebar.component.tsx
frontend/report-issue/report-issue.component.tsx
frontend/root.component.tsx
frontend/view-edit-client/interactions/add-client-interaction.component.tsx
frontend/view-edit-client/view-client.component.tsx

**In order to see this UI before Phase 2 is finished, you must run `localStorage.setItem('client-interactions', true)`**

Beginnings of client interactions page, including global add. See #184.

---

frontend/add-client/form-inputs/intake-services-inputs.component.tsx
frontend/add-client/services.component.tsx
frontend/util/state-select.component.tsx
package.json
yarn.lock

Now that we have the services grouped into programs, we can show them grouped by program in the Add/Edit client flow.

Grouping services by program in Add/Edit client

---

frontend/view-edit-client/client-home/view-edit-contact-info.component.tsx
frontend/view-edit-client/client-home/view-edit-demographics-info.component.tsx
frontend/view-edit-client/client-home/view-edit-intake-info.component.tsx

Notice how I forgot to remove the Edit buttons from Contact Information on the confirm add client page. This fixes that.

Removing Edit buttons from confirm add client page.

---

frontend/client-list/client-list.component.tsx

When switching between ascending/descending sort in the client list, or switching to a whole new column to sort on, it makes more sense to take you back to page 1 rather than keep you on page 2 or greater of the newly sorted data.
See #256

Resetting page to 1 whenever the sort changes.

---

api-docs/leads.md

Leads docs for phase 4. 
Per our conversation at the CU meeting age and gender were decided to be kept in as is since birth date will be picked up when converting to client replacing the age attribute and both age and gender are needed for event planning and reporting involving leads. 
Incorporated events as the source of the leads per the meeting conversation also.

Leads API docs  part 1 - get one

---

api-docs/events.md

Since they wanted to be able to use event info with the leads I'm also putting together the events api-docs to scope that out. We won't need the full events management part on the front end as part of this phase, but it appears we'll need at least part of the backend and a minimal frontend to cover the needs for the leads phase.
This PR gets us started on it.

events api docs part 1 - start and get one

---

docker-compose.yml

This might come in handy if you (like me) already run various db versions
on different ports.
Note that for this to work you need to put both RDS_PORT and DATABASE_URL
in your .env file, since db-migrate won't pick up the former in dev mode.

Make it possible to run mysql on a different port

---

frontend/view-edit-client/interactions/single-interaction-slat.component.tsx

See #328. I found the bug by downloading the elastic beanstalk logs. They showed the following:
```
[ 'Property interactionType must be one of the following: inPerson, byPhone, workshopTalk, oneOnOneLightTouch, consultation. Received \'oneOnOneLightTough\'' ]
POST /api/clients/112/interactions 400 165 - 0.829 ms
```
See [here](https://github.com/JustUtahCoders/comunidades-unidas-internal/blob/a14ebcc56675a76d7aff4a8926938ca3b8923b08/backend/apis/clients/client-interactions/create-client-interaction.api.js#L25) for why the 400 is occurring (just a typo in the request)

Fixing typo in oneOnOneLightTouch. Resolves #328.

---

package.json
yarn.lock

I broke the creation of JPLS participants right before publishing v1.1.0. This fixes it. See related https://github.com/JustUtahCoders/juntos-por-la-salud-node-client/releases/tag/v1.1.2

Upgrading juntos por la salud to fix a bug

---

frontend/leads-list/lead-list.component.tsx
frontend/navbar/use-full-width.hook.tsx

Using a hook inside of an if statement is a violation of the [rules of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level). Specifically the "Only Call Hooks At The Top Level" rule. Violating the rules of hooks can result in some really nasty bugs. We have the eslint plugin enabled to try to find violations of the rules of hooks, but it missed this one.

Fixing violation of React rules of hooks

---

README.md

For Windows users, I've added a section explaining to use the winpty tool that comes with Git for Windows.

Add details about winpty for Windows users

---

frontend/util/easy-fetch.ts
package.json
yarn.lock

Doesn't actually close the connection, but it does fail in-flight promises. Fixes blank screen issue on older versions of mobile safari.

Add AbortController polyfill, refs #425

---

backend/apis/reports/country-of-origin-report.api.js
docker-compose.yml

See #570 - this was caused by adding clients without a country of origin for the very first time yesterday as part of the Suite CRM migration.

Fix country of origin report when country is missing. Resolves #570.

---

backend/apis/reports/english-level.api.js
frontend/reports/english-levels/english-levels-params.component.tsx
frontend/reports/english-levels/english-levels-results.component.tsx

Issue: https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/582
Add start and end form fields for [english-levels](http://localhost:8080/reports/english-levels) that grabs rows between two dates (inclusive) based on `dateOfIntake`.

Add date range on dateOfIntake for english-levels

---

backend/apis/reports/country-of-origin-report.api.js
frontend/reports/country-of-origin/country-of-origin-params.component.tsx
frontend/reports/country-of-origin/country-of-origin-results.component.tsx

Issue: https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/582
Add start and end form fields for [countries-of-origin](http://localhost:8080/reports/countries-of-origin) that grabs rows between two dates (inclusive) based on `dateOfIntake`.

Add date range for dateOfIntake for countries-of-origin

---

backend/apis/reports/client-sources-report.api.js
frontend/reports/client-sources/client-sources-params.component.tsx
frontend/reports/client-sources/client-sources-results.component.tsx

Issue: https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/582
Add start and end form fields for [client-sources](http://localhost:8080/reports/client-sources) that grabs rows between two dates (inclusive) based on `dateOfIntake`.

Add date range on dateOfIntake for client-sources

---

backend/apis/reports/ages-and-genders-report.api.js
frontend/reports/ages-and-genders/ages-and-genders-params.component.tsx
frontend/reports/ages-and-genders/ages-and-genders-results.components.tsx

Issue: https://github.com/JustUtahCoders/comunidades-unidas-internal/issues/582
Add start and end form fields for [ages-and-genders](http://localhost:8080/reports/ages-and-genders) that grabs rows between two dates (inclusive) based on `dateOfIntake` for Clients and `dateOfSignUp` for Leads.
@joeldenning I think it is important to note that the start and end dates mean different things for clients and leads. Let me know if you want me to change how it displays the explanation.

Add date range for ages-and-genders

---

frontend/view-edit-lead/lead-home/lead-metadata.component.tsx
frontend/view-edit-lead/lead-home/lead-section.component.tsx
frontend/view-edit-lead/lead-home/view-edit-basic-lead-info.component.tsx

Fixes #694 
I chose to do it this way after examining other areas of the app. A contact has a similar header, it's slightly different but I tried to capture the look and feel with this change.
It didn't feel right in other areas and this area _felt_ the most visually consistent to me. If you want changes to the approach or location please let me know.

Adding lead metadata to lead basic info card

---

backend/apis/reports/interactions-by-service.api.js
frontend/reports/interactions-by-service/interactions-by-service-results.component.tsx

I noticed a couple of weird things while adding this UI.
1. Follow-ups aren't required to have an associated service. The follow-ups with unspecified services don't show up anywhere in this report or in the total. It seems misleading/confusing to me. Thoughts on adding an "unspecified" row? (this would also require a backend change, happy to do that)
2. If a follow-up is associated with multiple services, the "grand total" counts that same follow-up twice in the sums for count & duration. It seems like we want to change the backend reporting logic here -- I'm happy to do this, but because it's a nontrivial change I wanted to check if there is any reason we might want to keep this or maybe even change a follow-up to only be associated with 1 service.
For example:
Created a follow up for a …

UI for follow-ups in Interactions by Service report
